# Generated by Django 3.1.3 on 2020-12-07 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201126_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.user'),
            preserve_default=False,
        ),
    ]
